serviceAccounts:
  pushgateway:
    create: false

pushgateway:
  enabled: false

alertmanager:
  enabled: true
  persistentVolume:
    existingClaim: pvc-alertmanager
  service:
    type: NodePort
    nodePort: 32000
  securityContext:
    runAsNonRoot: false
    runAsUser: 0

server:
  persistentVolume:
    existingClaim: pvc-prometheus
  service:
    type: NodePort
    nodePort: 30000
  securityContext:
    runAsNonRoot: false
    fsGroup: 0
    runAsGroup: 0
    runAsUser: 0

alertmanagerFiles:
  alertmanager.yml:
    global:
      resolve_timeout: 5m
      #http_config:
       # proxy_url: 'http://www-proxy-hqdc.us.oracle.com:80'
    route:
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 1h
      receiver: 'web.hook'
      routes:
      - match:
          alertname: ScaleUpNotification
        receiver: web.hook.scaleup
      - match:
          alertname: ScaleDownNotification
        receiver: web.hook.scaledown
    receivers:
    - name: 'web.hook.scaleup'
      webhook_configs:
      - url: 'http://10.96.224.117:9000/hooks/scaleup'
    - name: 'web.hook.scaledown'
      webhook_configs:
      - url: 'http://10.96.224.117:9000/hooks/scaledown'
    - name: 'web.hook'
      webhook_configs:
      - url: 'http://10.96.224.117:9000/hooks'
    inhibit_rules:
      - source_match:
          severity: 'critical'
        target_match:
          severity: 'warning'
        equal: ['alertname', 'dev', 'instance']

serverFiles:
  alerts:
    groups:
      - name: weblogic_rules
        rules:
          - alert: ClusterWarning
            for: 1m
            expr: sum by(weblogic_domainUID, weblogic_clusterName) (up{weblogic_domainUID=~'.+'}) == 1
            labels:
              severity: page
            annotations:
              description: 'Some WLS cluster has only one running server for more than 1 minutes.'
              summary: 'Some wls cluster is in warning state.'
          - alert: ScaleUpNotification
            for: 1m
            expr: sum(wls_webapp_config_open_sessions_current_count{app="testwebapp"}) > 15
            labels:
              severity: page
            annotations:
              description: 'Scale up when current sessions is greater than 15.'
              summary: 'Firing alert when total sessions active greater than 15.'
          - alert: ScaleDownNotification
            for: 1m
            expr: sum(wls_webapp_config_open_sessions_current_count{app="testwebapp"}) < 15
            labels:
              severity: page
            annotations:
              description: 'Scale up when current sessions is greater than 15.'
              summary: 'Firing alert when total sessions active greater than 15.'

extraScrapeConfigs: |
    - job_name: 'wls-k8s-domain'
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_pod_label_weblogic_domainUID, __meta_kubernetes_pod_label_weblogic_clusterName]
        action: keep
        regex: wls-k8s-domain-ns;wls-k8s-domain;cluster-1
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: pod_name
      basic_auth:
        username: weblogic
        password: welcome1
